apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: 10-microservice-kubernetes
  region: ap-south-1

vpc:
  id: vpc-011f9381dc206bb27
  subnets:
    public:
      ap-south-1a:
        id: subnet-01c0534c80955892a
      ap-south-1b:
        id: subnet-065d24f195af343d8
      ap-south-1c:
        id: subnet-0d7064ab59d69853a

nodeGroups:
- name: ng-1
  instanceType: t3.small
  desiredCapacity: 2
  minSize: 2
  maxSize: 3
