name: Deploy to EKS

on:
  push:
    branches:
    - master
  workflow_dispatch:


jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_DEFAULT_REGION: 'ap-south-1' # Change to your AWS region
      CLUSTER_NAME: '10-microservice-kubernetes'
      NAMESPACE: 'default'
      MANIFEST_PATH: 'release/kubernetes-manifests.yaml'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_DEFAULT_REGION }}

    - name: Install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        pip3 install awscli

    - name: Configure kubectl
      run: |
        aws eks update-kubeconfig --name ${{ env.CLUSTER_NAME }} --region ${{ env.AWS_DEFAULT_REGION }}

    - name: Deploy to EKS
      run: |
        for file in ${{ env.MANIFEST_PATH }}/*.yaml; do
          kubectl apply -f $file -n ${{ env.NAMESPACE }};
        done
