name: Deploy to EKS

on:
  push:
    branches:
    - master
  workflow_dispatch:
    # Add this line to enable manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_DEFAULT_REGION: 'ap-south-1' # Change to your AWS region
      CLUSTER_NAME: '10-microservice-kubernetes'
      NAMESPACE: 'default'
      MANIFEST_PATH: 'release' # Update this to the correct path

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Print AWS Credentials (Masked)
      run: |
        echo "AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}"
        echo "AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}"
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_DEFAULT_REGION }}

    - name: Install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        pip3 install awscli

    - name: Configure kubectl
      run: |
        aws eks update-kubeconfig --name 10-microservice-kubernetes --region ap-south-1
        kubectl get nodes  # Verify that kubectl is configured correctly

    - name: Deploy to EKS
      run: |
        kubectl apply -f ${{ env.MANIFEST_PATH }}/kubernetes-manifests.yaml -n ${{ env.NAMESPACE }} --validate=false
